load_libraries_2<- function(){
  library(ggplot2)
  library(scales) 
  library(data.table)
  library(mvtnorm)
  library(rhdf5)
  library(HDF5Array)
  library(patchwork)
  library(cowplot)
  library(magick)
  library(raster)
  library(tibble)
  library(ggpubr)
  library(colorspace)
  library(grid)
  library(RColorBrewer)
  library(gridExtra)
  library(Seurat)
  #source("R/protein_kp/plot_protein.R") 
  #source("R/protein_kp/FeaturePlotKP.R", echo=TRUE)
  library(scMerge)
  source("src/protein_normalization.R")
  source("src/get_cell_membership_faster.R")
  source("src/droplet_analysis.R")
}